apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: k3s-wireguard-mgr
build:
  artifacts:
    - image: ghcr.io/bryopsida/k8s-wireguard-mgr
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - tests/k8s/job.yaml
verify:
  - name: verify-secret-created
    container:
      name: verify-secret-created
      image: ghcr.io/curium-rocks/wg-kubectl:main
      command:
        - kubectl
        - get
        - secret
        - test-wg-secret
    executionMode:
      kubernetesCluster:
        jobManifestPath: tests/k8s/verify-secret-created.yaml
  - name: verify-secret-works
    container:
      name: verify-secret-works
      image: ghcr.io/curium-rocks/wg-kubectl:main
      command: ["/bin/sh"]
      args: ["-c", "cat /wg/privatekey | tee | wg pubkey"]
    executionMode:
      kubernetesCluster:
        jobManifestPath: tests/k8s/verify-secret-works-with-wg.yaml
